name:
  Cron Job

on:
  # Triggers the workflow every friday at 9:05 UTC, 4:05 EDT
  schedule:
    - cron: "5 21 * * 5"
  # Ability to run manually  
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
        type: choice
        options:
        - info
        - warning
        - debug
 
jobs:
  update:
    runs-on: ubuntu-latest
    steps:
    # Downloads repo
      - name: Checkout
        uses: 'actions/checkout@v3'
        with:
          fetch-depth: 0
          persist-credentials: false
    # Inits repo and runs script
      - name: Install dependencies
        uses: VaultVulp/action-pipenv@v2.0.1
        with:
        command: install -d # Install all dependencies, including development ones
      - name: Run script
        run: python3 index.py
        timeout-minutes: 10
    